# Generated by Django 2.2.2 on 2019-10-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='imageInfo',
            field=models.ImageField(blank=True, upload_to='ImageInfo'),
        ),
    ]
