# Generated by Django 2.2.6 on 2019-10-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testb', '0002_test_imageinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='lon',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
