# Generated by Django 2.2.6 on 2019-10-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testb', '0003_auto_20191023_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='boxChecked',
            field=models.BooleanField(default=False),
        ),
    ]
