# Generated by Django 2.2.6 on 2019-10-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testb', '0004_test_boxchecked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='test',
            name='imageInfo',
            field=models.ImageField(upload_to='ImageInfo'),
        ),
    ]
